global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'redis_exporter'
    static_configs:
      - targets: ['redis_exporter:9121']

